spring.application.name=printing-backend
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=university_printing

jwt.secret=${JWT_SECRET:c2VjdXJlX3VuaXZlcnNpdHlfcHJpbnRpbmdfcGxhdGZvcm1fc2VjcmV0X2tleV8yNTZiaXRzX2Zvcl9qd3RfYXV0aGVudGljYXRpb24=}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}

# Multipart Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.url=${CLOUDINARY_URL:}